#!/bin/sh
exec java -cp . -Xbootclasspath/a:.:3rdparty/truffle/truffle-api-19.2.0.1.jar:nqp-runtime.jar:3rdparty/asm/asm-4.1.jar:3rdparty/jline/jline-1.0.jar:3rdparty/jna/jna-4.0.0.jar:nqp.jar nqp "$@"
