#!perl
use v5.12;
use warnings;
use File::Slurp qw(slurp);

my $tests = slurp('src/vm/js/bin/run_tests.pl'); 

my ($match) = $tests =~ /my \@nqp_tests = glob "(t\/nqp\/\{[0-9,]+\}\*)/;

my @tests = glob $match;

my %tests;
$tests{$_}++ for @tests;

my @all = <t/nqp/*.t>;
for (@all) {
    say $_ unless $tests{$_};
}
