=head1 Bootstrapping procedure for NQP

NPQ is a bootstrapped compiler, which means that it uses itself to compile
itself.

To make the first compilation possible, a compiled version of the compiler is
stored in F</src/stage0/*.moarvm> and included in the source code repository.

When you make changes to the compiler, eventually you need to update these
I<stage0> files.

Here is how you proceed to update the bootstrapping files in nqp.  At any
stage, if C<make test> fails, don't go ahead with the following steps, but fix
the problem first.

=over

=item *

Make your changes, run C<make test>

=item *

Run C<make m-bootstrap-files> and C<make test>

=item *

Commit the non-bootstrap files that you modified yourself

=item *

Commit the bootstrap files

=back

Historic References: L<http://irclog.perlgeek.de/perl6/2010-04-22#i_2253227>
